import java.lang.String;
import java.io.Serializable;
// Class generated by EMF from Ecore model
public class ClassA_1 implements Serializable {
    // attributes ...

	public static void main(String[] args) {
	}
}