class Foo {
   String  id;
   String  name;
   Integer value;

    @Override // override equals method for the class (Foo)
    public boolean equals(Object o) {
        if (!(o instanceof Foo)) return false;
        final Foo other = (Foo) o;
        return this.id != null ? this.id.equals(other.id) : other.id == null;
    }

   /* Generated by Eclipse, note that field name and value are not included here */
   @Override // override hashCode method for the class (Foo)
   public int hashCode() {
       final int prime = 31;
       int result = 1;
       return prime * result + ((id == null) ? 0 : id.hashCode());
   }
}